services:
  telebackup:
    image: ghcr.io/aiexz/telebackup:master
    environment:
      APP_ID: 6
      APP_HASH: 123
      BOT_TOKEN: 123:abc
      TARGET: 123
      TARGETS: |
        /test
        /test2
    volumes:
      - /tmp/test:/tmp/test:ro
      - /tmp/test2:/tmp/test2:ro
# or use this if you want to use a config file and not environment variables
#    volumes:
#      - ./config.yml:/config.yml